import type { SalesRow } from "./types";

/**
 * Fallback sample data — used when the Google Sheet CSV is unreachable.
 * Mirrors the real sheet's column structure.
 */
export const SAMPLE_ROWS: SalesRow[] = [
  {
    detailProduk: "MP",
    tanggal: "1/2/2026",
    namaKlien: "Lely Puspitasari",
    sesi: 0,
    emailProduk: "",
    nominal: 69000,
    namaSales: "MS PRILLY",
    kategori: "MP 1 Bulan",
    jenisProduk: "KONSELING BUNDLING SENIOR 2",
    status: "NEW",
    jenisLayanan: "MP",
    kategori2: "NON TA",
  },
  {
    detailProduk: "MP",
    tanggal: "1/2/2026",
    namaKlien: "Feni Purba",
    sesi: 0,
    emailProduk: "",
    nominal: 69000,
    namaSales: "MS SHINTA",
    kategori: "MP 1 Bulan",
    jenisProduk: "MHCU",
    status: "NEW",
    jenisLayanan: "MP",
    kategori2: "NON TA",
  },
  {
    detailProduk: "MP",
    tanggal: "1/2/2026",
    namaKlien: "Sherly Aprilia Maryani",
    sesi: 0,
    emailProduk: "",
    nominal: 69000,
    namaSales: "MS AYU",
    kategori: "MP 1 Bulan",
    jenisProduk: "MHCU",
    status: "NEW",
    jenisLayanan: "MP",
    kategori2: "NON TA",
  },
  {
    detailProduk: "MP",
    tanggal: "1/2/2026",
    namaKlien: "Luckyanto Wijaya",
    sesi: 0,
    emailProduk: "",
    nominal: 69000,
    namaSales: "MS AYU",
    kategori: "MP 1 Bulan",
    jenisProduk: "MHCU",
    status: "NEW",
    jenisLayanan: "MP",
    kategori2: "NON TA",
  },
  // Additional sample rows to populate the dashboard
  {
    detailProduk: "MP",
    tanggal: "2/2/2026",
    namaKlien: "Dewi Lestari",
    sesi: 1,
    emailProduk: "",
    nominal: 138000,
    namaSales: "MS YUYUN",
    kategori: "MP 2 Bulan",
    jenisProduk: "MHCU",
    status: "NEW",
    jenisLayanan: "MP",
    kategori2: "NON TA",
  },
  {
    detailProduk: "MP",
    tanggal: "3/2/2026",
    namaKlien: "Rina Marlina",
    sesi: 0,
    emailProduk: "",
    nominal: 69000,
    namaSales: "MS ARINA",
    kategori: "MP 1 Bulan",
    jenisProduk: "MHCU",
    status: "NEW",
    jenisLayanan: "MP",
    kategori2: "NON TA",
  },
  {
    detailProduk: "MP",
    tanggal: "4/2/2026",
    namaKlien: "Siti Nurhaliza",
    sesi: 2,
    emailProduk: "",
    nominal: 207000,
    namaSales: "MS NUR",
    kategori: "MP 3 Bulan",
    jenisProduk: "MHCU",
    status: "NEW",
    jenisLayanan: "MP",
    kategori2: "NON TA",
  },
  {
    detailProduk: "MP",
    tanggal: "5/2/2026",
    namaKlien: "Dhea Ananda",
    sesi: 0,
    emailProduk: "",
    nominal: 69000,
    namaSales: "MS DHEA",
    kategori: "MP 1 Bulan",
    jenisProduk: "MHCU",
    status: "NEW",
    jenisLayanan: "MP",
    kategori2: "NON TA",
  },
  {
    detailProduk: "MP",
    tanggal: "6/2/2026",
    namaKlien: "Gita Dwi Cahyani",
    sesi: 1,
    emailProduk: "",
    nominal: 138000,
    namaSales: "MS GDC",
    kategori: "MP 2 Bulan",
    jenisProduk: "MHCU",
    status: "NEW",
    jenisLayanan: "MP",
    kategori2: "NON TA",
  },
  {
    detailProduk: "MP",
    tanggal: "7/2/2026",
    namaKlien: "Keke Putri",
    sesi: 0,
    emailProduk: "",
    nominal: 69000,
    namaSales: "MS KEKE",
    kategori: "MP 1 Bulan",
    jenisProduk: "MHCU",
    status: "NEW",
    jenisLayanan: "MP",
    kategori2: "NON TA",
  },
  {
    detailProduk: "HADIR",
    tanggal: "8/2/2026",
    namaKlien: "Budi Santoso",
    sesi: 1,
    emailProduk: "",
    nominal: 150000,
    namaSales: "MS AYU",
    kategori: "HADIR",
    jenisProduk: "HADIR",
    status: "NEW",
    jenisLayanan: "HADIR",
    kategori2: "TA",
  },
  {
    detailProduk: "WP",
    tanggal: "9/2/2026",
    namaKlien: "Agus Wijaya",
    sesi: 1,
    emailProduk: "",
    nominal: 200000,
    namaSales: "MS SHINTA",
    kategori: "WP",
    jenisProduk: "WP",
    status: "NEW",
    jenisLayanan: "WP",
    kategori2: "TA",
  },
  {
    detailProduk: "MHCU",
    tanggal: "10/2/2026",
    namaKlien: "PT Maju Jaya",
    sesi: 3,
    emailProduk: "",
    nominal: 500000,
    namaSales: "MS PRILLY",
    kategori: "MHCU FOR COMPANY",
    jenisProduk: "MHCU",
    status: "NEW",
    jenisLayanan: "MHCU FOR COMPANY",
    kategori2: "TA",
  },
  {
    detailProduk: "MP",
    tanggal: "11/2/2026",
    namaKlien: "Indah Permata",
    sesi: 0,
    emailProduk: "",
    nominal: 69000,
    namaSales: "MS YUYUN",
    kategori: "MP 1 Bulan",
    jenisProduk: "MHCU",
    status: "NEW",
    jenisLayanan: "MP",
    kategori2: "NON TA",
  },
  {
    detailProduk: "MP",
    tanggal: "12/2/2026",
    namaKlien: "Rahmat Hidayat",
    sesi: 1,
    emailProduk: "",
    nominal: 138000,
    namaSales: "MS ARINA",
    kategori: "MP 2 Bulan",
    jenisProduk: "MHCU",
    status: "NEW",
    jenisLayanan: "MP",
    kategori2: "NON TA",
  },
  {
    detailProduk: "MP",
    tanggal: "13/2/2026",
    namaKlien: "Putri Ayu",
    sesi: 0,
    emailProduk: "",
    nominal: 69000,
    namaSales: "MS NUR",
    kategori: "MP 1 Bulan",
    jenisProduk: "MHCU",
    status: "NEW",
    jenisLayanan: "MP",
    kategori2: "NON TA",
  },
  {
    detailProduk: "MP",
    tanggal: "14/2/2026",
    namaKlien: "Rizky Pratama",
    sesi: 2,
    emailProduk: "",
    nominal: 207000,
    namaSales: "MS DHEA",
    kategori: "MP 3 Bulan",
    jenisProduk: "MHCU",
    status: "NEW",
    jenisLayanan: "MP",
    kategori2: "NON TA",
  },
  {
    detailProduk: "MP",
    tanggal: "15/2/2026",
    namaKlien: "Sari Wulandari",
    sesi: 0,
    emailProduk: "",
    nominal: 69000,
    namaSales: "MS GDC",
    kategori: "MP 1 Bulan",
    jenisProduk: "MHCU",
    status: "NEW",
    jenisLayanan: "MP",
    kategori2: "NON TA",
  },
  {
    detailProduk: "MP",
    tanggal: "16/2/2026",
    namaKlien: "Andi Firmansyah",
    sesi: 1,
    emailProduk: "",
    nominal: 138000,
    namaSales: "MS KEKE",
    kategori: "MP 2 Bulan",
    jenisProduk: "MHCU",
    status: "NEW",
    jenisLayanan: "MP",
    kategori2: "NON TA",
  },
  {
    detailProduk: "HADIR",
    tanggal: "17/2/2026",
    namaKlien: "Citra Kirana",
    sesi: 1,
    emailProduk: "",
    nominal: 150000,
    namaSales: "MS PRILLY",
    kategori: "HADIR",
    jenisProduk: "HADIR",
    status: "NEW",
    jenisLayanan: "HADIR",
    kategori2: "TA",
  },
  {
    detailProduk: "WP",
    tanggal: "18/2/2026",
    namaKlien: "Dedi Kurniawan",
    sesi: 2,
    emailProduk: "",
    nominal: 400000,
    namaSales: "MS AYU",
    kategori: "WP",
    jenisProduk: "WP",
    status: "NEW",
    jenisLayanan: "WP",
    kategori2: "TA",
  },
  {
    detailProduk: "MHCU",
    tanggal: "19/2/2026",
    namaKlien: "PT Sejahtera",
    sesi: 2,
    emailProduk: "",
    nominal: 350000,
    namaSales: "MS SHINTA",
    kategori: "MHCU FOR COMPANY",
    jenisProduk: "MHCU",
    status: "NEW",
    jenisLayanan: "MHCU FOR COMPANY",
    kategori2: "TA",
  },
  {
    detailProduk: "MP",
    tanggal: "20/2/2026",
    namaKlien: "Eka Prasetya",
    sesi: 0,
    emailProduk: "",
    nominal: 69000,
    namaSales: "MS YUYUN",
    kategori: "MP 1 Bulan",
    jenisProduk: "MHCU",
    status: "NEW",
    jenisLayanan: "MP",
    kategori2: "NON TA",
  },
  {
    detailProduk: "MP",
    tanggal: "21/2/2026",
    namaKlien: "Fajar Nugroho",
    sesi: 1,
    emailProduk: "",
    nominal: 138000,
    namaSales: "MS ARINA",
    kategori: "MP 2 Bulan",
    jenisProduk: "MHCU",
    status: "NEW",
    jenisLayanan: "MP",
    kategori2: "NON TA",
  },
  {
    detailProduk: "MP",
    tanggal: "22/2/2026",
    namaKlien: "Gina Safitri",
    sesi: 0,
    emailProduk: "",
    nominal: 69000,
    namaSales: "MS NUR",
    kategori: "MP 1 Bulan",
    jenisProduk: "MHCU",
    status: "NEW",
    jenisLayanan: "MP",
    kategori2: "NON TA",
  },
  {
    detailProduk: "MP",
    tanggal: "23/2/2026",
    namaKlien: "Hendra Gunawan",
    sesi: 1,
    emailProduk: "",
    nominal: 138000,
    namaSales: "MS DHEA",
    kategori: "MP 2 Bulan",
    jenisProduk: "MHCU",
    status: "NEW",
    jenisLayanan: "MP",
    kategori2: "NON TA",
  },
  {
    detailProduk: "MP",
    tanggal: "24/2/2026",
    namaKlien: "Intan Permatasari",
    sesi: 0,
    emailProduk: "",
    nominal: 69000,
    namaSales: "MS GDC",
    kategori: "MP 1 Bulan",
    jenisProduk: "MHCU",
    status: "NEW",
    jenisLayanan: "MP",
    kategori2: "NON TA",
  },
  {
    detailProduk: "MP",
    tanggal: "25/2/2026",
    namaKlien: "Joko Susilo",
    sesi: 2,
    emailProduk: "",
    nominal: 207000,
    namaSales: "MS KEKE",
    kategori: "MP 3 Bulan",
    jenisProduk: "MHCU",
    status: "NEW",
    jenisLayanan: "MP",
    kategori2: "NON TA",
  },
  {
    detailProduk: "HADIR",
    tanggal: "26/2/2026",
    namaKlien: "Kartika Sari",
    sesi: 1,
    emailProduk: "",
    nominal: 150000,
    namaSales: "MS AYU",
    kategori: "HADIR",
    jenisProduk: "HADIR",
    status: "NEW",
    jenisLayanan: "HADIR",
    kategori2: "TA",
  },
  {
    detailProduk: "WP",
    tanggal: "27/2/2026",
    namaKlien: "Lukman Hakim",
    sesi: 1,
    emailProduk: "",
    nominal: 200000,
    namaSales: "MS PRILLY",
    kategori: "WP",
    jenisProduk: "WP",
    status: "NEW",
    jenisLayanan: "WP",
    kategori2: "TA",
  },
  {
    detailProduk: "MHCU",
    tanggal: "28/2/2026",
    namaKlien: "PT Berkah Abadi",
    sesi: 4,
    emailProduk: "",
    nominal: 600000,
    namaSales: "MS SHINTA",
    kategori: "MHCU FOR COMPANY",
    jenisProduk: "MHCU",
    status: "NEW",
    jenisLayanan: "MHCU FOR COMPANY",
    kategori2: "TA",
  },
];